{
    "name": "Risk Module",
    "version": "19.0.1.0.0",
    "category": "Impocoma",
    "author": "Angel",
    "website": "https://www.impocoma.com",
    "summary": "Modulo para el departamento de riesgo en Impocoma",
    "depends": ["base", "website", "mail", "portal", "auth_signup"],
    "data": [
        "data/risk_signup_config.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/risk_submission_mail_templates.xml",
        "views/risk_submission_report_actions.xml",
        "views/risk_submission_report_styles.xml",
        "views/risk_submission_report_templates.xml",
        "views/risk_submission_document_views.xml",
        "views/risk_external_validation_views.xml",
        "views/risk_submission_list_views.xml",
        "views/risk_submission_form_views.xml",
        "views/risk_submission_search_views.xml",
        "views/risk_signup_login_views.xml",
        "views/risk_submission_actions.xml",
        "views/risk_approval_wizard_views.xml",
        "views/risk_external_validation_result_wizard_views.xml",
        "views/risk_submission_menus.xml",
        "views/website_risk_submission_step_vehicle.xml",
        "views/website_risk_submission_step_owner.xml",
        "views/website_risk_submission_step_driver.xml",
        "views/website_risk_submission_step_terms.xml",
        "views/website_risk_submission_step_signatures.xml",
        "views/website_risk_submission_step_review.xml",
        "views/website_risk_submission_terms_modal.xml",
        "views/website_risk_submission_success.xml",
        "views/website_risk_submission_portal.xml",
        "views/website_risk_submission_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "risk_module/static/src/css/risk_submission.css",
            "risk_module/static/src/js/risk_submission_vehicle.js",
            "risk_module/static/src/js/risk_submission_owner.js",
            "risk_module/static/src/js/risk_submission_terms.js",
            "risk_module/static/src/js/risk_submission_signatures.js",
            "risk_module/static/src/js/risk_submission_print.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
