{
    "name": "Risk Module",
    "version": "19.0.1.0.2",
    "category": "Impocoma",
    "author": "Angel",
    "website": "https://www.impocoma.com",
    "summary": "Modulo para el departamento de riesgo en Impocoma",
    "depends": ["base", "website", "mail", "portal", "auth_signup"],
    "external_dependencies": {"python": ["msal", "requests"]},
    "data": [
        "data/risk_signup_config.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/risk_document_requirements.xml",
        "data/risk_message_templates.xml",
        "data/risk_sharepoint_cron.xml",
        "views/mail/risk_submission_mail_templates.xml",
        "views/reports/risk_submission_report_actions.xml",
        "views/reports/risk_submission_report_styles.xml",
        "views/reports/risk_submission_report_templates.xml",
        "views/backend/risk_document_requirement_views.xml",
        "views/backend/risk_message_template_views.xml",
        "views/wizards/risk_document_reject_wizard_views.xml",
        "views/backend/risk_submission_document_views.xml",
        "views/backend/risk_external_validation_views.xml",
        "views/backend/risk_master_views.xml",
        "views/backend/risk_submission_list_views.xml",
        "views/backend/risk_submission_form_views.xml",
        "views/backend/risk_submission_search_views.xml",
        "views/website/risk_signup_login_views.xml",
        "views/backend/risk_submission_actions.xml",
        "views/wizards/risk_approval_wizard_views.xml",
        "views/wizards/risk_external_validation_result_wizard_views.xml",
        "views/backend/res_config_settings_views.xml",
        "views/backend/risk_submission_menus.xml",
        "views/backend/risk_process_views.xml",
        "views/website/website_risk_submission_step_vehicle.xml",
        "views/website/website_risk_submission_step_owner.xml",
        "views/website/website_risk_submission_step_driver.xml",
        "views/website/website_risk_submission_step_terms.xml",
        "views/website/website_risk_submission_step_signatures.xml",
        "views/website/website_risk_submission_step_review.xml",
        "views/website/website_risk_submission_terms_modal.xml",
        "views/website/website_risk_submission_success.xml",
        "views/website/website_risk_submission_portal.xml",
        "views/website/website_risk_submission_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "risk_module/static/src/css/risk_backend.css",
        ],
        "web.assets_frontend": [
            "risk_module/static/src/css/risk_submission.css",
            "risk_module/static/src/css/risk_portal_detail.css",
            "risk_module/static/src/js/risk_municipios.js",
            "risk_module/static/src/js/risk_submission_vehicle.js",
            "risk_module/static/src/js/risk_submission_owner.js",
            "risk_module/static/src/js/risk_submission_driver.js",
            "risk_module/static/src/js/risk_submission_terms.js",
            "risk_module/static/src/js/risk_submission_signatures.js",
            "risk_module/static/src/js/risk_otp.js",
            "risk_module/static/src/js/risk_submission_print.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
